### ISSUE TITLE
Error testing on Windows

### ISSUE THREAD

**Issue by moyadin** [Zoltan99/Zoltan#1]
Hello, Zoltan!

Here are the steps I followed:

- Installed Crawler successfully and tested it
- Started downloading
- After a bit, clicked Ctrl + C to terminate process [(Y/N)? I clicked Y]
- Downloaded the zip file. Opened Python 3.5 IDE. F5 to run the code. (couldn't get it to run following your steps)
- Pasted the original destination
- Pasted the desired destination
- Got this error:

Traceback (most recent call last):
  File "M:\Zoltan-master\letolto.py", line 36, in <module>
    f = open(konyvtar+"tmp/"+keresesi_cim+".json", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'M:\\Skill-Share-Crawler---DL-master\\videos\\Drawing Monsters with Adobe Illustrator CCtmp/Time to draw some monsters.json'

What do you think the error is? Thanks

**Comment by Zoltan99** [comment]
Hello!
I have not tested on windows.
I think, you have the absoluth path false.
Do you have forgotten by the end a \ simbol.

M:\Skill-Share-Crawler---DL-master\videos\Drawing Monsters with Adobe
Illustrator CC

Use so please:
M:\Skill-Share-Crawler---DL-master\videos\Drawing Monsters with Adobe
Illustrator CC\

Dont forget re run the Crawler. The token experied soon.
So you got errors.



Moayad <notifications@github.com> ezt írta (időpont: 2020. jan. 6., H 4:51):

**Comment by moyadin** [comment]
Thanks for the quick response. Here is an equally follow up before testing final results. Adding the "\" fixed the issue. It seems to work fine.
However, you said 

> Dont forget re run the Crawler. The token experied soon. So you got  errors.

Does that mean I go through manual auth and leave it be or redownload the course itself?
Is it something I do once or do I keep "manual auth" every couple of hours?

Another side note: It seems to be working fine so far but super slow. Any reason why?

Thank you!

UPDATE: I got this error just now

```
34455555Traceback (most recent call last):
  File "M:\Libraries\Zoltan-master\letolto.py", line 53, in <module>
    urlretrieve(src, hely, reporthook)
  File "C:\Python35-32\lib\urllib\request.py", line 228, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 21075600 out of 34455555 bytes>
```

**Comment by Zoltan99** [comment]
Does that mean I go through manual auth and leave it be or redownload the
course itself?

If works, nothing to do.



Moayad <notifications@github.com> ezt írta (időpont: 2020. jan. 6., H
10:50):

**Comment by moyadin** [comment]
Thank you. However, it doesn't work. The module shell keeps filling with lines (the progress) and slows down dramatically and quickly. After a while it stops completely and this message appears:

`34455555Traceback (most recent call last):
File "M:\Libraries\Zoltan-master\letolto.py", line 53, in <module>
  urlretrieve(src, hely, reporthook)
File "C:\Python35-32\lib\urllib\request.py", line 228, in urlretrieve
  % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 21075600 out of 34455555 bytes>`

**Comment by Zoltan99** [comment]
Hello!
I have tested on windows 7 64. It works fine.
Just won't use python idle, use the **cmd** promt!
Navigate to letolto.py script folder in cmd line.
Start the program with: **python letolto.py**
It works!

**Comment by moyadin** [comment]
Thank you very much!

I did that. To navigate to the designated folder I typed "cmd" in front of the path in Windows Explorer.

I then typed "python letolto.py" to run your program. However, I got this message:
```
Traceback (most recent call last):
  File "letolto.py", line 4, in <module>
    from urllib.request import urlretrieve
ImportError: No module named request
```

Did I do anything wrong?

Update: Since I have to install Python 2 for the Crawler to work I wanted to make sure that I am running Python 3. I read online that I have to simply write "python3 letolto.py" to run the program in that specific version. However, when I do that literally nothing happens. I see a new line of cmd in the same directory. I tried it couple of times and I get the same result.

**Comment by Zoltan99** [comment]
Hy! Install please python 3.6.

Moayad <notifications@github.com> ezt írta (időpont: 2020. jan. 9., Cs
14:54):
